# Generated by Django 6.0.7 on 2026-08-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('inn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'measures',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('record_link', models.CharField(blank=True, max_length=255)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contacts', to='crm.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contacts', to='crm.contact')),
            ],
            options={
                'db_table': 'company_contact',
                'unique_together': {('company', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(related_name='companies', through='crm.CompanyContact', to='crm.contact'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('keywords', models.TextField(blank=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='crm.material', verbose_name='Родительский материал')),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.measure')),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='CompanyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_materials', to='crm.company')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_materials', to='crm.material')),
            ],
            options={
                'db_table': 'company_material',
                'unique_together': {('company', 'material')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='materials',
            field=models.ManyToManyField(related_name='companies', through='crm.CompanyMaterial', to='crm.material'),
        ),
        migrations.CreateModel(
            name='MeetingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_companies', to='crm.company')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_companies', to='crm.meeting')),
            ],
            options={
                'db_table': 'meeting_company',
                'unique_together': {('meeting', 'company')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='companies',
            field=models.ManyToManyField(related_name='meetings', through='crm.MeetingCompany', to='crm.company'),
        ),
        migrations.CreateModel(
            name='MeetingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_contacts', to='crm.contact')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_contacts', to='crm.meeting')),
            ],
            options={
                'db_table': 'meeting_contact',
                'unique_together': {('meeting', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='contacts',
            field=models.ManyToManyField(related_name='meetings', through='crm.MeetingContact', to='crm.contact'),
        ),
        migrations.CreateModel(
            name='MeetingEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_employees', to='crm.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_employees', to='crm.meeting')),
            ],
            options={
                'db_table': 'meeting_employee',
                'unique_together': {('meeting', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='employees',
            field=models.ManyToManyField(related_name='meetings', through='crm.MeetingEmployee', to='crm.employee'),
        ),
    ]
