# Generated by Django 6.0.7 on 2026-08-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_company_mail_company_phone_companycontact_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
