# Generated by Django 6.0.7 on 2026-08-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_parent_id_material_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
