# Generated by Django 6.0.7 on 2026-08-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_company_mail_alter_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
