# Generated by Django 6.0.7 on 2026-08-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('record_link', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meetings',
                'managed': False,
            },
        ),
    ]
